# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];
 
   boot.loader = {
    systemd-boot = {
      enable = true;
      memtest86.enable = false;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3aa41af7-89ac-484f-92c4-629d186dce2e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/388A-B614";
      fsType = "vfat";
    };

  fileSystems."/mnt/storage" =
    { device = "storage";
      fsType = "zfs";
    };

  boot.zfs.extraPools = [ "storage" ];

  boot.zfs.forceImportRoot = false;

  swapDevices = [ { device = "/dev/disk/by-uuid/ce7f3bf8-8e9a-4d98-bd2b-26bfad3d4baf"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
