{
  ...
}:{
  imports = [
    ./ollama.nix
    ./nginx.nix
    ./sshd.nix
    ./nextcloud.nix
    ./postgresql.nix
    ./netdata.nix
    ./examia.nix
    ./hedgedoc.nix
    ./zulip.nix
    ./passbolt.nix
    ./minecraft.nix
    ./fsim-room-tunnel.nix
    ./engelsystem.nix
    ./znapzend.nix
    ./wiki-js.nix
    ./emacs.nix
  ];
}
